# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cred',
            name='date',
        ),
    ]
